// ECO code to opening name mapping.
//
// Covers, at minimum, every code the repertoire uses: this map is what the
// heroes gallery's opening search offers, so a code missing from here could
// not be picked at all, and rendered as a bare "D01" wherever it appeared.
// Nine of the repertoire's 23 codes used to be missing.
export const ecoNames: Record<string, string> = {
  "A05": "Reti Opening",
  "A10": "English Opening",
  "A11": "English: Caro-Kann Defensive System",
  "A12": "English: Slav, Bled Variation",
  "A13": "English: Agincourt Defense",
  "A14": "English: Neo-Catalan",
  "A15": "English: Anglo-Indian",
  "A16": "English: Anglo-Grunfeld",
  "A20": "English: King's English",
  "A21": "English: King's English, Smyslov",
  "A25": "English: Sicilian Reversed",
  "A26": "English: Botvinnik System",
  "A29": "English: Four Knights",
  "A30": "English: Symmetrical",
  "A37": "English Symmetrical",
  "A39": "English: Symmetrical, Main Line",
  "A45": "Indian Game",
  "A46": "Indian: London System",
  "A48": "Indian: London / Torre / Colle",
  "A56": "Benoni Defense",
  "A60": "Benoni: Modern, Fianchetto",
  "A61": "Benoni: Modern, Bg5 / Nf3",
  "A62": "Benoni: Fianchetto Variation",
  "A65": "Benoni: King's Pawn Storm",
  "A66": "Benoni: Four Pawns, Pawn Storm",
  "A67": "Benoni: Taimanov Variation",
  "A68": "Benoni: Four Pawns Attack",
  "A70": "Benoni: Modern, Main Line",
  "A71": "Benoni: Classical, Bg5",
  "A72": "Benoni: Classical without 9.O-O",
  "A73": "Benoni: Classical, 9.O-O",
  "A76": "Benoni: Classical, Re1",
  "A77": "Benoni: Classical, Nd7",
  "B20": "Sicilian Defense",
  "B21": "Sicilian: Smith-Morra",
  "B22": "Sicilian: Alapin",
  "B23": "Sicilian: Closed / Grand Prix",
  "B25": "Sicilian: Closed",
  "B26": "Sicilian: Closed",
  "B30": "Sicilian: Old Sicilian",
  "B31": "Sicilian: Nyezhmetdinov-Rossolimo",
  "B32": "Sicilian: Open",
  "B34": "Sicilian: Accelerated Dragon",
  "B35": "Sicilian: Accelerated Dragon, Bc4",
  "B36": "Sicilian: Accelerated Dragon, Maroczy",
  "B37": "Sicilian: Accelerated Dragon",
  "B38": "Sicilian: Maroczy Bind, Be3",
  "B39": "Sicilian: Maroczy Bind, Breyer",
  "D01": "Richter-Veresov / Jobava London",
  "E60": "King's Indian Defense",
  "E61": "King's Indian: Classical",
  "E90": "King's Indian: 5.Nf3",
  "E91": "King's Indian: Classical"
};
